#
# Copyright (c) 2023, NIPPON TELEGRAPH AND TELEPHONE CORPORATION
#
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: sh

    strategy:
      fail-fast: false
      matrix:
        version:
          - 16
          - 15
          - 14
          - 13
          - 12

    env:
      PGVERSION: ${{ matrix.version }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install pg
      run: |
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -v $PGVERSION -p -i
        sudo -u postgres createuser -s "$USER"

    - name: build
      run: |
        make PROFILE="-Werror" USE_PGXS=1
        sudo -E make install USE_PGXS=1

    - name: configure shared_preload_libraries
      run: |
        psql -c 'alter system set shared_preload_libraries = pg_stat_statements, pg_store_plans' postgres
        sudo service postgresql restart

    - name: test
      run: |
        make installcheck USE_PGXS=1

    - name: show regression diffs
      if: ${{ failure() }}
      run: |
        cat regression.diffs
